apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: takabee0306/auth-depl
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: takabee0306/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "**/*.js"
            dest: .
    - image: takabee0306/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: takabee0306/orders
      context: orders
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: takabee0306/expiration
      context: expiration
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: takabee0306/payments
      context: payments
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .